import React from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { useAuth } from '../components/Common/AuthContext';
import { RevenueChart, OccupancyChart, AttendanceLineChart } from '../components/Admin/Analytics';
import { analyticsApi } from '../services/api';
import { 
  TrendingUp, 
  Users, 
  Calendar, 
  DollarSign,
  Download,
  Plus,
  BarChart,
  CheckCircle2,
  Ticket,
  ShieldCheck,
  FileSpreadsheet,
  FileText,
  MapPin,
  ArrowRight,
  User
} from 'lucide-react';
const StatCard = ({ title, value, icon: Icon, trend }) => (
  <div className="glass-card p-6">
    <div className="flex justify-between items-start mb-4">
      <div className="p-3 bg-white/5 rounded-xl border border-white/10">
        <Icon className="w-6 h-6 text-event-gold" />
      </div>
      <span className={`text-sm font-medium ${trend.startsWith('+') ? 'text-green-400' : 'text-red-400'}`}>
        {trend}
      </span>
    </div>
    <h3 className="text-gray-400 text-sm mb-1">{title}</h3>
    <p className="text-2xl font-bold">{value}</p>
  </div>
);
const Dashboard = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [stats, setStats] = React.useState(null);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    if (user?.role === 'attendee') {
      navigate('/dashboard/bookings');
      return;
    }
  }, [user, navigate]);

  React.useEffect(() => {
    const fetchStats = async () => {
      try {
        const data = await analyticsApi.getPlatformStats();
        setStats(data);
      } catch (error) {
        console.error('Error fetching stats:', error);
      } finally {
        setLoading(false);
      }
    };
    if (user.role === 'admin') fetchStats();
    else setLoading(false);
  }, [user.role]);

  
  const getGreeting = () => {
    switch (user.role) {
      case 'admin': return 'System Overview';
      case 'manager': return 'Events Hub Dashboard';
      default: return `Welcome back, ${user.name}`;
    }
  };

  const getSubtext = () => {
    switch (user.role) {
      case 'admin': return 'Full visibility into Rwanda EventHub metrics and user access.';
      case 'manager': return 'Manage your schedules, speakers, and venue check-ins.';
      default: return 'Explore your booked experiences and digital tickets.';
    }
  };

  const handleExportPDF = () => {
    const doc = new jsPDF();
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(212, 175, 55);
    doc.text("Rwanda EventHub", 14, 20);
    
    doc.setFontSize(16);
    doc.setTextColor(40, 40, 40);
    doc.text("System Performance Report", 14, 30);
    
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated by: ${user.name} (${user.role.toUpperCase()})`, 14, 40);
    doc.text(`Date Extracted: ${new Date().toLocaleDateString()}`, 14, 46);

    const tableColumn = ["Event Name", "Status", "Revenue (RWF)", "Check-ins", "Capacity Utilized"];
    const tableRows = [
      ["Rwanda Tech Summit", "Active", "8,500,000", "850/900", "94%"],
      ["Creative Expo Kigali", "Upcoming", "2,100,000", "0/500", "40%"],
      ["Startup Investment Mixer", "Completed", "1,850,000", "330/330", "100%"]
    ];

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 55,
      theme: 'grid',
      headStyles: { fillColor: [212, 175, 55], textColor: [0, 0, 0] },
      styles: { fontSize: 10, cellPadding: 4 }
    });

    const finalY = doc.lastAutoTable.finalY || 55;
    
    doc.setFont("helvetica", "bold");
    doc.setTextColor(40, 40, 40);
    doc.text("Financial Summary (By Ticket Class)", 14, finalY + 15);
    
    autoTable(doc, {
       head: [["Ticket Category", "Total Sales", "Gross Revenue (RWF)"]],
       body: [
         ["VVIP Tickets", "52", "5,200,000"],
         ["VIP Tickets", "76", "3,800,000"],
         ["Regular Tickets", "163", "2,450,000"],
         ["General Admission", "100", "1,000,000"]
       ],
       startY: finalY + 25,
       theme: 'grid',
       headStyles: { fillColor: [40, 40, 40], textColor: [255, 255, 255] }
     });

    doc.save(`EventHub_Report_${new Date().getTime()}.pdf`);
  };

  const handleExportExcel = () => {
    const overviewData = [
      ["Rwanda EventHub - System Overview"],
      ["Date Generated", new Date().toLocaleDateString()],
      ["Generated By", user.name],
      ["Role", user.role.toUpperCase()],
      [],
      ["Key Metrics", "Value"],
      ["Total Revenue", "12,450,000 RWF"],
      ["Total Check-ins", "1,180"],
      ["Active System Users", "8"],
      ["Total Events", "18"]
    ];

    const eventsData = [
      ["Event Name", "Status", "Revenue (RWF)", "Check-ins", "Capacity"],
      ["Rwanda Tech Summit", "Active", "8500000", "850", "94%"],
      ["Creative Expo Kigali", "Upcoming", "2100000", "0", "40%"],
      ["Startup Investment Mixer", "Completed", "1850000", "330", "100%"]
    ];

    const wb = XLSX.utils.book_new();
    const wsOverview = XLSX.utils.aoa_to_sheet(overviewData);
    const wsEvents = XLSX.utils.aoa_to_sheet(eventsData);

    wsOverview['!cols'] = [{ wch: 25 }, { wch: 20 }];
    wsEvents['!cols'] = [{ wch: 30 }, { wch: 15 }, { wch: 20 }, { wch: 15 }, { wch: 15 }];

    XLSX.utils.book_append_sheet(wb, wsOverview, "System Overview");
    XLSX.utils.book_append_sheet(wb, wsEvents, "Event Metrics");

    XLSX.writeFile(wb, `EventHub_Metrics_${new Date().getTime()}.xlsx`);
  };

  return (
    <div className="space-y-8 pb-20">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div>
          <h1 className="text-4xl font-bold tracking-tight">{getGreeting()}</h1>
          <p className="text-[var(--text-secondary)] mt-1">{getSubtext()}</p>
        </div>
        <div className="flex flex-wrap gap-3">
          {(user.role === 'admin' || user.role === 'manager') && (
            <>
              <button 
                onClick={handleExportExcel}
                className="glass-button flex items-center space-x-2 text-sm bg-blue-500/10 border-blue-500/20 text-blue-400 hover:bg-blue-500/20 transition-colors"
              >
                <FileSpreadsheet className="w-4 h-4" />
                <span>Excel Export</span>
              </button>
              <button 
                onClick={handleExportPDF}
                className="glass-button flex items-center space-x-2 text-sm bg-red-500/10 border-red-500/20 text-red-400 hover:bg-red-500/20 transition-colors"
              >
                <FileText className="w-4 h-4" />
                <span>PDF Report</span>
              </button>
            </>
          )}
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {user.role === 'admin' ? (
          <>
            <StatCard title="Total Revenue" value={`${stats?.totalRevenue || 0} RWF`} icon={DollarSign} trend="+12.5%" />
            <StatCard title="System Users" value={stats?.totalUsers || 0} icon={Users} trend="+2 new" />
            <StatCard title="Global Capacity" value={stats?.totalCapacity || 0} icon={ShieldCheck} trend="95% ready" />
            <StatCard title="Total Events" value={stats?.totalEvents || 0} icon={Calendar} trend="+4 active" />
          </>
        ) : user.role === 'manager' ? (
          <>
            <StatCard title="My Events Revenue" value="2,750,000 RWF" icon={DollarSign} trend="+5.2%" />
            <StatCard title="Check-ins Today" value="1,180" icon={TrendingUp} trend="84%" />
            <StatCard title="Active Staff" value="4" icon={Users} trend="Online" />
            <StatCard title="Pending Approvals" value="3" icon={Calendar} trend="High Priority" />
          </>
        ) : (
          <>
            <StatCard title="Active Tickets" value={JSON.parse(localStorage.getItem('myBookings') || '[]').length} icon={Ticket} trend="Gate Ready" />
            <StatCard title="Rewards Points" value={JSON.parse(localStorage.getItem('myBookings') || '[]').length * 250} icon={TrendingUp} trend="Gold Tier" />
            <StatCard title="Past Events" value="0" icon={CheckCircle2} trend="View History" />
            <StatCard title="Saved Venues" value="2" icon={MapPin} trend="Quick Book" />
          </>
        )}
      </div>

      {/* Attendee Premium View */}
      {user.role === 'attendee' && (
        <div className="grid lg:grid-cols-3 gap-8">
           <div className="lg:col-span-2 space-y-8">
              <div className="glass-card p-10 relative overflow-hidden group">
                 <div className="absolute top-0 right-0 w-64 h-64 bg-event-gold/5 blur-[80px] rounded-full -mr-32 -mt-32" />
                 <h3 className="text-2xl font-black italic uppercase tracking-tighter mb-8 flex items-center">
                    <div className="w-8 h-1 bg-event-gold mr-4 rounded-full" />
                    Identity Protocol
                 </h3>
                 
                 <div className="flex flex-col md:flex-row items-center gap-10">
                    <div className="w-32 h-32 rounded-[2rem] bg-gradient-to-br from-event-gold/20 to-transparent border border-event-gold/30 flex items-center justify-center p-4 relative">
                       <User className="w-16 h-16 text-event-gold" />
                       <div className="absolute -bottom-2 -right-2 bg-green-500 w-6 h-6 rounded-full border-4 border-[#050505] shadow-lg shadow-green-500/40" />
                    </div>
                    <div className="flex-1 text-center md:text-left">
                       <p className="text-sm font-black text-event-gold uppercase tracking-[0.3em] mb-1">Authenticated Guest</p>
                       <h2 className="text-4xl font-black mb-4">{user.name}</h2>
                       <div className="flex flex-wrap justify-center md:justify-start gap-4">
                          <div className="px-4 py-1.5 rounded-full bg-white/5 border border-white/10 text-[10px] font-black uppercase tracking-widest text-gray-400">Verified Identity</div>
                          <div className="px-4 py-1.5 rounded-full bg-event-gold/10 border border-event-gold/20 text-[10px] font-black uppercase tracking-widest text-event-gold">VVIP Access</div>
                       </div>
                    </div>
                 </div>
              </div>

              <div className="glass-card p-8">
                 <h3 className="text-xl font-bold mb-6 flex items-center gap-3">
                    <Calendar className="w-5 h-5 text-event-gold" />
                    <span>Recent Activity Stream</span>
                 </h3>
                 <div className="space-y-6">
                    {JSON.parse(localStorage.getItem('myBookings') || '[]').length > 0 ? (
                      JSON.parse(localStorage.getItem('myBookings') || '[]').slice(0, 3).map(b => (
                        <div key={b.id} className="flex items-start gap-6 p-4 rounded-2xl hover:bg-white/5 transition-all border border-transparent hover:border-white/5 group">
                           <div className="w-12 h-12 bg-event-gold/10 rounded-xl flex items-center justify-center text-event-gold group-hover:scale-110 transition-transform">
                              <Ticket className="w-6 h-6" />
                           </div>
                           <div className="flex-1">
                              <div className="flex justify-between items-start">
                                 <h4 className="font-bold text-lg">{b.event}</h4>
                                 <span className="text-[10px] font-black text-gray-600">JUST NOW</span>
                              </div>
                              <p className="text-xs text-[var(--text-secondary)] mt-1">Digital ticket issued and secure seat <span className="text-event-gold font-bold">{b.seats[0]}</span> confirmed.</p>
                           </div>
                        </div>
                      ))
                    ) : (
                      <div className="py-10 text-center text-gray-500 italic">No recent system activity. Time to book an experience?</div>
                    )}
                 </div>
              </div>
           </div>

           <div className="space-y-8">
              <div className="glass-card p-8 bg-event-gold/5 border-event-gold/20">
                 <h3 className="font-black text-xs uppercase tracking-[0.3em] text-event-gold mb-6">Tactical Wallet</h3>
                 <div className="mb-8">
                    <p className="text-[10px] text-gray-500 font-bold uppercase mb-1">Available Loyalty Points</p>
                    <p className="text-5xl font-black italic tracking-tighter">{JSON.parse(localStorage.getItem('myBookings') || '[]').length * 250}</p>
                 </div>
                 <button className="btn-primary w-full py-4 text-xs font-black uppercase tracking-widest shadow-xl shadow-event-gold/20">Redeem Rewards</button>
              </div>

              <div className="glass-card p-8">
                 <h3 className="font-bold mb-6">Quick Links</h3>
                 <div className="space-y-3">
                    <button onClick={() => navigate('/dashboard/bookings')} className="w-full flex items-center justify-between p-4 bg-white/5 rounded-xl hover:bg-event-gold hover:text-black transition-all group">
                       <span className="font-bold text-sm">Access My Tickets</span>
                       <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                    </button>
                    <button onClick={() => navigate('/')} className="w-full flex items-center justify-between p-4 bg-white/5 rounded-xl hover:bg-event-gold hover:text-black transition-all group">
                       <span className="font-bold text-sm">Explore New Events</span>
                       <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                    </button>
                 </div>
              </div>
           </div>
        </div>
      )}

      {/* Analytics Grid - Only for Admin/Manager */}
      {(user.role === 'admin' || user.role === 'manager') && (
        <div className="grid lg:grid-cols-3 gap-6">
          <div className="lg:col-span-2 glass-card p-8">
            <div className="flex justify-between items-center mb-8">
              <div>
                <h3 className="text-xl font-bold flex items-center space-x-2">
                  <BarChart className="w-6 h-6 text-event-gold" />
                  <span>Revenue by Seat Type (RWF)</span>
                </h3>
                <p className="text-xs text-[var(--text-secondary)] mt-1">Real-time comparison across VVIP, VIP, Regular, and General classes.</p>
              </div>
            </div>
            <RevenueChart />
          </div>
          
          <div className="glass-card p-8 flex flex-col items-center">
            <h3 className="font-bold w-full text-left mb-8 text-xl">Venue Utilization</h3>
            <div className="w-full max-w-[200px] mb-8 relative">
                <OccupancyChart />
                <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
                    <p className="text-3xl font-black">84%</p>
                    <p className="text-[10px] text-gray-500 uppercase tracking-widest">Occupancy</p>
                </div>
            </div>
            <div className="w-full space-y-4">
              <div className="flex justify-between text-sm">
                <span className="text-[var(--text-secondary)] font-medium">Total Check-ins</span>
                <span className="font-black text-green-500">1,180 / 1,400</span>
              </div>
              <div className="w-full h-2 bg-white/5 rounded-full overflow-hidden border border-white/5">
                <div className="w-[84%] h-full bg-gradient-to-r from-event-gold to-yellow-500 shadow-[0_0_10px_rgba(212,175,55,0.4)]" />
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Dashboard;
