import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Ticket, Calendar, MapPin, QrCode, Download, Printer, CheckCircle2, MoreHorizontal } from 'lucide-react';
import jsPDF from 'jspdf';

const Bookings = () => {
  const [showQR, setShowQR] = useState(null);
  const [bookings, setBookings] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState('All');

  const MOCK_BOOKINGS = [
    { 
      id: "REH-2026-001", 
      event: "Rwanda Tech Summit 2026", 
      date: "May 15-17, 2026", 
      location: "Convention Centre", 
      seats: ["VVIP #01", "VVIP #02"], 
      status: "confirmed",
      price: "100,000 RWF",
      qr: "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=REH-2026-001-VAL-OK"
    },
    { 
      id: "REH-2026-042", 
      event: "Creative Expo", 
      date: "July 20-22, 2026", 
      location: "Kigali Heights", 
      seats: ["Regular #142"], 
      status: "pending_payment",
      price: "15,000 RWF",
      qr: ""
    }
  ];

  useEffect(() => {
    const saved = JSON.parse(localStorage.getItem('myBookings') || '[]');
    setBookings(saved);
  }, []);

  const filteredBookings = bookings.filter(b => {
    const matchSearch = b.event.toLowerCase().includes(searchTerm.toLowerCase()) || 
                        b.location.toLowerCase().includes(searchTerm.toLowerCase()) ||
                        b.id.toLowerCase().includes(searchTerm.toLowerCase());
    const matchStatus = statusFilter === 'All' || b.status === statusFilter;
    return matchSearch && matchStatus;
  });

  const handleDownloadPDF = async (booking) => {
    const doc = new jsPDF();
    
    // Background
    doc.setFillColor(10, 10, 10);
    doc.rect(0, 0, 210, 297, 'F');
    
    // Gold Accent Sidebar
    doc.setFillColor(212, 175, 55);
    doc.rect(0, 0, 12, 297, 'F');

    // Brand Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(26);
    doc.setTextColor(212, 175, 55);
    doc.text("RWANDA EVENT HUB", 25, 35);
    
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text("OFFICIAL VENUE ADMISSION PASS • SECURE TICKET", 25, 45);

    doc.setDrawColor(40, 40, 40);
    doc.line(25, 55, 190, 55);

    // Event Info
    doc.setFontSize(20);
    doc.setTextColor(255, 255, 255);
    doc.text(booking.event.toUpperCase(), 25, 75);

    const info = [
      { l: "BOOKING ID", v: booking.id },
      { l: "DATE & TIME", v: booking.date },
      { l: "VENUE", v: booking.location },
      { l: "SEAT(S)", v: booking.seats.join(', ') },
      { l: "PRICE", v: booking.price }
    ];

    let y = 95;
    info.forEach(item => {
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(item.l, 25, y);
      doc.setFontSize(11);
      doc.setTextColor(255, 255, 255);
      doc.text(String(item.v), 25, y+6);
      y += 20;
    });

    // QR Code Integration
    if (booking.qr) {
       doc.setDrawColor(212, 175, 55);
       doc.rect(130, 90, 60, 60);
       try {
         // Embed QR 
         doc.addImage(booking.qr, 'PNG', 135, 95, 50, 50);
       } catch (e) {
         console.error("QR Error:", e);
       }
       doc.setFontSize(8);
       doc.setTextColor(212, 175, 55);
       doc.text("SCAN AT VENUE GATE", 143, 155);
    }

    // Security Footer
    doc.setFontSize(7);
    doc.setTextColor(60, 60, 60);
    doc.text("This document is a valid legal ticket for the mentioned event. Please keep it confidential.", 25, 275);
    doc.text("Generated by Rwanda EventHub Tactical Platform. Security Code: " + booking.id + "-REH", 25, 280);

    doc.save(`Ticket_${booking.id}.pdf`);
  };

  return (
    <div className="space-y-8">
      <div className="flex flex-col lg:flex-row gap-6 p-4 bg-white/5 rounded-3xl border border-white/5">
         <div className="relative flex-1 group">
            <Search className="absolute left-5 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-700 group-focus-within:text-event-gold transition-colors" />
            <input 
              type="text" 
              placeholder="Search your tickets by event, location or ID..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full bg-black/40 border border-white/10 rounded-2xl py-4 pl-14 pr-6 focus:border-event-gold outline-none font-bold placeholder:text-gray-800 transition-all text-sm"
            />
         </div>
         <div className="flex items-center space-x-3">
            <span className="text-[10px] font-black uppercase text-gray-600 tracking-widest">Filter:</span>
            <select 
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="bg-black/40 border border-white/10 rounded-2xl px-6 py-4 text-[10px] font-black uppercase tracking-widest focus:border-event-gold outline-none cursor-pointer"
            >
               <option value="All">All Vouchers</option>
               <option value="confirmed">Confirmed</option>
               <option value="Checked In">Checked In</option>
               <option value="pending_payment">Pending</option>
            </select>
         </div>
      </div>

      <div className="grid gap-6">
        {filteredBookings.length === 0 ? (
          <div className="glass-card p-16 flex flex-col items-center justify-center text-center">
            <div className="w-20 h-20 bg-white/5 rounded-full flex items-center justify-center mb-6 border-2 border-dashed border-white/10">
              <Ticket className="w-8 h-8 text-[var(--text-secondary)]" />
            </div>
            <h3 className="text-xl font-bold mb-2">No bookings yet</h3>
            <p className="text-[var(--text-secondary)] mb-6">Browse our upcoming events to get started and secure your tickets.</p>
            <a href="/" className="btn-primary flex items-center space-x-2">
              <Calendar className="w-5 h-5" />
              <span>Browse Events</span>
            </a>
          </div>
        ) : filteredBookings.map((booking) => (
          <div key={booking.id} className="glass-card overflow-hidden group">
            <div className="flex flex-col md:flex-row divide-y md:divide-y-0 md:divide-x divide-[var(--border-color)]">
              {/* Left Info */}
              <div className="p-8 flex-1 space-y-6">
                 <div className="flex justify-between items-start">
                    <div>
                      <span className={`text-[10px] uppercase tracking-widest font-black px-2 py-0.5 rounded border ${
                        booking.status === 'Checked In' ? 'bg-green-500/20 text-green-500 border-green-500/40' :
                        booking.status === 'confirmed' ? 'bg-blue-500/10 text-blue-500 border-blue-500/20' : 
                        'bg-yellow-500/10 text-yellow-500 border-yellow-500/20'
                      }`}>
                        {booking.status === 'Checked In' ? 'Admission Authorized' : 
                         booking.status === 'confirmed' ? 'Payment Verified' : 'Awaiting MoMo'}
                      </span>
                      <h2 className="text-2xl font-bold mt-3 group-hover:text-event-gold transition-colors">{booking.event}</h2>
                    </div>
                    <p className="text-xs font-medium text-[var(--text-secondary)]">Ref: {booking.id}</p>
                 </div>

                 <div className="flex flex-wrap gap-6">
                    <div className="flex items-center space-x-2 text-sm">
                      <Calendar className="w-4 h-4 text-event-gold" />
                      <span>{booking.date}</span>
                    </div>
                    <div className="flex items-center space-x-2 text-sm text-[var(--text-secondary)]">
                      <MapPin className="w-4 h-4" />
                      <span>{booking.location}</span>
                    </div>
                    <div className="flex items-center space-x-2 text-sm text-[var(--text-secondary)] font-bold">
                      <Ticket className="w-4 h-4 text-event-gold" />
                      <span>{booking.seats.join(', ')}</span>
                    </div>
                 </div>
              </div>

              {/* Right Actions */}
              <div className="p-8 md:w-80 bg-white/[0.02] flex flex-col justify-between space-y-6">
                 <div className="flex justify-between items-center">
                    <p className="text-xs text-[var(--text-secondary)] font-bold uppercase">Total Paid</p>
                    <p className="text-xl font-black text-event-gold">{booking.price}</p>
                 </div>

                 <div className="grid grid-cols-1 gap-3">
                    {booking.status === 'confirmed' ? (
                      <button 
                        onClick={() => setShowQR(booking)}
                        className="btn-primary w-full flex items-center justify-center space-x-2 py-3"
                      >
                        <QrCode className="w-4 h-4" />
                        <span>View QR Ticket</span>
                      </button>
                    ) : (
                      <button className="glass-button w-full flex items-center justify-center space-x-2 py-3 border-yellow-500/20 text-yellow-500">
                        <span>Retry Payment</span>
                      </button>
                    )}
                    <button 
                      onClick={() => handleDownloadPDF(booking)}
                      className="glass-button w-full flex items-center justify-center space-x-2 py-3"
                    >
                      <Download className="w-4 h-4" />
                      <span>PDF Receipt</span>
                    </button>
                 </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      <AnimatePresence>
        {showQR && (
          <div className="fixed inset-0 z-[70] flex items-center justify-center p-6 bg-black/90 backdrop-blur-md">
             <motion.div 
               initial={{ opacity: 0, scale: 0.9 }}
               animate={{ opacity: 1, scale: 1 }}
               exit={{ opacity: 0, scale: 0.9 }}
               className="bg-white rounded-[2.5rem] p-10 max-w-sm w-full text-black text-center relative"
             >
                <button onClick={() => setShowQR(null)} className="absolute top-6 right-6 p-2 hover:bg-black/5 rounded-full">
                  <MoreHorizontal className="w-6 h-6" />
                </button>
                
                <div className="mb-8">
                  <div className="w-16 h-16 bg-event-gold rounded-2xl flex items-center justify-center mx-auto mb-4 rotate-12">
                     <Ticket className="w-8 h-8 text-black -rotate-12" />
                  </div>
                  <h3 className="text-xl font-black uppercase tracking-tighter italic">Rwanda EventHub</h3>
                </div>

                <div className="bg-gray-100 p-6 rounded-3xl mb-8">
                   <img src={showQR.qr} alt="QR Code" className="w-full aspect-square mix-blend-multiply" />
                   <div className="mt-4 pt-4 border-t border-gray-200">
                      <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Scannable Guest ID</p>
                      <p className="font-mono text-sm tracking-widest mt-1">{showQR.id}</p>
                   </div>
                </div>

                <div className="space-y-4">
                   <div>
                      <p className="text-lg font-black">{showQR.event}</p>
                      <p className="text-xs font-bold text-gray-500">{showQR.seats.join(' + ')}</p>
                   </div>
                   <div className="flex space-x-3">
                      <button className="flex-1 bg-black text-white py-4 rounded-2xl font-bold flex items-center justify-center space-x-2">
                        <Printer className="w-4 h-4" />
                        <span>Print Hub</span>
                      </button>
                      <button className="flex-1 bg-gray-100 py-4 rounded-2xl font-bold flex items-center justify-center space-x-2">
                        <Download className="w-4 h-4" />
                        <span>Save</span>
                      </button>
                   </div>
                </div>
                
                <p className="mt-8 text-[10px] text-gray-400 font-bold uppercase leading-relaxed">
                  Present this QR code at the {showQR.location} for instant venue entry.
                </p>
             </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default Bookings;
